; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATmega48]
platform = atmelavr
board = ATmega48
;framework = baremetal
upload_protocol = usbasp
upload_flags = -e ;refresh the chip before upload
board_fuses.lfuse = 0xE7 ;this fuse setup is for 8MHz external crystal
board_fuses.hfuse = 0xDF
board_fuses.efuse = 0xFF